DROP TABLE event IF EXISTS;

-- -----------------------------------------------------------------------------

CREATE TABLE event
(
    ID          bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 5),
    name        varchar(100) NOT NULL,
    event_date  date         NOT NULL,
    description varchar(100),
    PRIMARY KEY (id)
);
